[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[dn]
CN = prx-golang-b42-pr-golang.runflare.cloud

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = prx-golang-b42-pr-golang.runflare.cloud
